- name: Add epel-release repo
  yum:
    name: epel-release
    state: present


- name: Install nginx
  yum:
    name: nginx
    state: present


- name: change UID user nginx
  user:
    name: nginx
    uid: 1121


- name: change gid user nginx
  group:
    name: nginx
    gid: 1120


- name: Start NGiNX
  service:
    name: nginx
    state: started
