- name: Disable SELinux
  selinux:
    state: disabled
  become: yes


vi /etc/selinux/config

- hosts: wiki
  tasks:
  - lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: 'SELINUX=disabled'
