- name: Désactiver temporairement SELinux
  selinux:
    state: disabled
  become: yes


- name: Désactiver définitivement SELinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
