---
- name: installwikib
  hosts: wiki
  become: yes
  roles:
     - name: Arborescence
     - name: signature
     - name: SElinux
     - name: reboot
     - name: unzip
     - name: tools
     - name: depot_package1
     - name: nginx
     - name: firewall
     - name: php
     - name: config_nginx
     - name: mariadb
     - name: MariadbDatabase
     - name: config_mariadb
     - name: reboot
     - name: SiPbNginx
     - name: fullrestart
     - name: installwiki
     - name: reboot
     - name: SiPbNginx
     - name: fullrestart
     - name: importDonnees
     - name: rebuildchanges
     - name: importImages
     - name: cookiesLocalSettings
     - name: reboot
     - name: SiPbNginx
     - name: fullrestart

#V2 Migration
    #- name: majPHP74
    #- name: automysqlbackup
    #- name: wikisave
    #- name: depot_package2
    #- name: LocalSettingsV2
    #- name: unlink
    #- name: importNouvellesImages
    #- name: installphp-mbstring
    #- name: updatewiki
