- name: Crer le répertoire utilisateur de webadm
  file:
    path: /home/webadm
    state: directory
    recurse: yes

- name: Creer les répertoires de livraison contenant les versions
  file:
    path: /appli/LIVR/version1
    state: directory
    recurse: yes
  file:
    path: /appli/LIVR/version2
    state: directory
    recurse: yes

- name: Creer le repertoire projects
  file:
    path: /appli/projects/wikib/mariadb/mysql/mysql
    state: directory
    recurse: yes
  file:
    path: /appli/projects/wikib/mariadb/mysql/wikib
    state: directory
    recurse: yes
  file:
    path: /appli/projects/wikib/nginx/version1/data
    state: directory
    recurse: yes
  file:
    path: /appli/projects/wikib/nginx/version1/data/images
    state: directory
    recurse: yes
  file:
    path: /appli/projects/wikib/nginx/version1/wiki_devops
    state: directory
    recurse: yes
  file:
    path: /appli/projects/wikib/nginx/version2
    state: directory
    recurse: yes

- name: Creer le repertoire projects
  file:
    path: /appli/data
    state: directory
    recurse: yes

- name: Creer le repertoire projects
  file:
    path: /var/projects/wikib/nginx
    state: directory
    recurse: yes

- name: Creer le repertoire projects
  file:
    path: /var/projects/wikib/mariadb
    state: directory
    recurse: yes


- name: Creer dossier du livrable
  file:
    path: /appli/mediawiki/LIVR/01.00.00
    state: directory
