- name: stop mariadb
  service:
    name: mariadb
    state: stopped


- name: Synchronization database dans le FS
  synchronize:
    src: /var/lib/mysql
    dest: rsync://appli/projects/wikib/mariadb
    

- name: déplacer et renommer mysql en mysql.bak
  command: mv /var/lib/mysql /var/lib/mysql.bak
  when: mysql.stat.exists == true


- name: Create mariadb my.cnf
  template:
    src: roles/config_mariadb/templates/new_maria_my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

- name: Create symlink for database old new
  file:
    path: /appli/projects/wikib/mariadb/mysql
    dest: /var/lib/mysql
    state: link
    force: yes
