- name: stop mariadb
  service:
    name: mariadb
    state: stopped


- name: Synchronization origin database config and FS config
  synchronize:
    src: /var/lib/mysql
    dest: /appli/projects/wikib/mariadb/mysql
    checksum: yes
    archive: no
    links: yes
    recursive: yes
    delete: yes
    rsync_opts:
      - "--include=*.conf"
      - "--exclude=*"


- name: statut de mysql
  stat: /var/lib/mysql
  register: mysql


- name: déplacer et renommer mysql en mysql.bak
  command: mv /var/lib/mysql /var/lib/mysql.bak
  when: mysql.stat.exists == true


- name: Create mariadb my.cnf
  template:
    src: roles/config_mariadb/templates/new_maria_my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

- name: Create symlink for database old new
  file:
    path: /appli/projects/wikib/mariadb/mysql
    dest: /var/lib/mysql
    state: link
    force: yes
