- name: Install epel release
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: copier le repo à installer
  copy:
     src: files/remi-release-7.rpm
     dest: /home/webadm/repo.rpm

- name: Install rpm
  command: rpm -Uvh /home/webadm/repo.rpm
  ignore_errors: true

- name: install repo
  yum:
    name: "{{ item }}"
    enablerepo: remi-php74
    state: present
  loop:
    - php
    - php-xml
    - php-mcrypt
    - php-cli
    - php-curl
    - php-ldap
    - php-soap
    - php-xmlrpc
    - php-mbstring
    - php-json
    - php-gd
    - php-zip
    - php-fileinfo
    - php-mcrypt
    - php-mysql
    - php74-php-intl
    - php-fpm
  ignore_errors: true
