- name: install php74
  yum:
    name: "{{ item }}"
    enablerepo: remi-php74
    state: present
  loop:
    - php74
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-ldap
    - php-zip
    - php-fileinfo
    - php-xml
    - php-fpm
