- name: Remove php
  yum:
    name: php
    state: absent

- name: Install remi repo
  yum:
    name: "{{ remi_repo_url }}"
    state: present

- name: configure repo
  command: yum-config-manager --enable remi-php74

- name: install php74
  yum:
    name: "{{ item }}"
    enablerepo: remi-php74
    state: present
  loop:
    - php
    - php
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-ldap
    - php-zip 
    - php-fileinfo
    - php-xml
    - php-fpm
