- name: Vérifier si le LocalSettings existe
  stat:
    path: /appli/projects/wikib/nginx/version1/wiki_devops/LocalSettings.php
  register: stat_result

- name: commande install.php
  command: php /appli/projects/wikib/nginx/version1/wiki_devops/maintenance/install.php --confpath=/usr/share/nginx/html/wikib --dbname=wikib --dbpass=password --globals --dbuser=userwikib --lang=fr --memory-limit=max --pass=azerty123 --scriptpath=/wikib wikib Admin
  when: stat_result.stat.exists == False
