- name: Create new nginx.conf
  template:
    src: roles/config_nginx/templates/new_nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Create new www.conf
  template:
    src: roles/config_nginx/templates/new_www.conf.j2
    dest: /etc/php-fpm.d/www.conf

- name: Creer le lien entre dépôt et serveur nginx
  command: ln -s /appli/projects/wikib/nginx/version1/wiki_devops /usr/share/nginx/html/wikib
