- firewalld:
    service: http
    zone: public
    permanent: yes
    state: enabled

- firewalld:
    service: https
    zone: public
    permanent: yes
    state: enabled

- name: Reboot du firewall
  command: firewall-cmd --reload
