- name: kill processus du port 80
  command: sudo fuser 80/tcp

- name: start nginx
  service:
    name: nginx
    state: started

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
